### ISSUE TITLE
KmerCamel doesn't need to be included as a submodule

### ISSUE THREAD

**Issue by karel-brinda** [OndrejSladky/fmsi#34]
If the goal of this is only to include it on Bioconda, this can be done more easily by specifying it as a Bioconda dependency.

**Comment by OndrejSladky** [comment]
Currently, FMSI uses the internals of KmerCamel (fixed to a specific version) for the experimental features of compaction while doing set operations.
Once I revisit these experimental operations, I might remove the dependency on KmerCamel's internals, but for now I don't see a better option for it than including it in the repo.
